<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit72ee3da5d4b1cd3825af65ed1eab3295
{
    public static $prefixLengthsPsr4 = array (
        'C' =>
        array (
            'Config\\' => 7,
        ),
        'A' =>
        array (
            'App\\Models\\' => 11,
            'App\\Controllers\\' => 16,
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Config\\' =>
        array (
            0 => __DIR__ . '/../..' . '/Config',
        ),
        'App\\Models\\' =>
        array (
            0 => __DIR__ . '/../..' . '/app/Models',
        ),
        'App\\Controllers\\' =>
        array (
            0 => __DIR__ . '/../..' . '/app/Controllers',
        ),
        'App\\' =>
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit72ee3da5d4b1cd3825af65ed1eab3295::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit72ee3da5d4b1cd3825af65ed1eab3295::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit72ee3da5d4b1cd3825af65ed1eab3295::$classMap;

        }, null, ClassLoader::class);
    }
}
