<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Config\\' => array($baseDir . '/Config'),
    'App\\Models\\' => array($baseDir . '/app/Models'),
    'App\\Controllers\\' => array($baseDir . '/app/Controllers'),
    'App\\' => array($baseDir . '/app'),
);
